/**
 * RAL Classic Farbpalette — Mapping RAL-Code → Hex + lokalisierte Namen.
 * Quelle: RAL gGmbH (Deutsch + offizielle Englisch-Bezeichnungen), gerundete sRGB-Werte.
 *
 * Struktur: { hex, names: { 'de-DE': string, 'en-GB': string } }
 * Locale-Auflösung erfolgt im Plugin-JS mit Fallback auf 'de-DE'.
 */
export default {
    'RAL 1000': { hex: '#BEBD7F', names: { 'de-DE': 'Grünbeige', 'en-GB': 'Green beige' } },
    'RAL 1001': { hex: '#C2B078', names: { 'de-DE': 'Beige', 'en-GB': 'Beige' } },
    'RAL 1002': { hex: '#C6A664', names: { 'de-DE': 'Sandgelb', 'en-GB': 'Sand yellow' } },
    'RAL 1003': { hex: '#E5BE01', names: { 'de-DE': 'Signalgelb', 'en-GB': 'Signal yellow' } },
    'RAL 1004': { hex: '#CDA434', names: { 'de-DE': 'Goldgelb', 'en-GB': 'Golden yellow' } },
    'RAL 1005': { hex: '#A98307', names: { 'de-DE': 'Honiggelb', 'en-GB': 'Honey yellow' } },
    'RAL 1006': { hex: '#E4A010', names: { 'de-DE': 'Maisgelb', 'en-GB': 'Maize yellow' } },
    'RAL 1007': { hex: '#DC9D00', names: { 'de-DE': 'Narzissengelb', 'en-GB': 'Daffodil yellow' } },
    'RAL 1011': { hex: '#8A6642', names: { 'de-DE': 'Braunbeige', 'en-GB': 'Brown beige' } },
    'RAL 1012': { hex: '#C7B446', names: { 'de-DE': 'Zitronengelb', 'en-GB': 'Lemon yellow' } },
    'RAL 1013': { hex: '#EAE6CA', names: { 'de-DE': 'Perlweiß', 'en-GB': 'Oyster white' } },
    'RAL 1014': { hex: '#E1CC4F', names: { 'de-DE': 'Elfenbein', 'en-GB': 'Ivory' } },
    'RAL 1015': { hex: '#E6D690', names: { 'de-DE': 'Hellelfenbein', 'en-GB': 'Light ivory' } },
    'RAL 1016': { hex: '#EDFF21', names: { 'de-DE': 'Schwefelgelb', 'en-GB': 'Sulfur yellow' } },
    'RAL 1017': { hex: '#F5D033', names: { 'de-DE': 'Safrangelb', 'en-GB': 'Saffron yellow' } },
    'RAL 1018': { hex: '#F8F32B', names: { 'de-DE': 'Zinkgelb', 'en-GB': 'Zinc yellow' } },
    'RAL 1019': { hex: '#9E9764', names: { 'de-DE': 'Graubeige', 'en-GB': 'Grey beige' } },
    'RAL 1020': { hex: '#999950', names: { 'de-DE': 'Olivgelb', 'en-GB': 'Olive yellow' } },
    'RAL 1021': { hex: '#F3DA0B', names: { 'de-DE': 'Rapsgelb', 'en-GB': 'Rape yellow' } },
    'RAL 1023': { hex: '#FAD201', names: { 'de-DE': 'Verkehrsgelb', 'en-GB': 'Traffic yellow' } },
    'RAL 1024': { hex: '#AEA04B', names: { 'de-DE': 'Ockergelb', 'en-GB': 'Ochre yellow' } },
    'RAL 1026': { hex: '#FFFF00', names: { 'de-DE': 'Leuchtgelb', 'en-GB': 'Luminous yellow' } },
    'RAL 1027': { hex: '#9D9101', names: { 'de-DE': 'Currygelb', 'en-GB': 'Curry' } },
    'RAL 1028': { hex: '#F4A900', names: { 'de-DE': 'Melonengelb', 'en-GB': 'Melon yellow' } },
    'RAL 1032': { hex: '#D6AE01', names: { 'de-DE': 'Ginstergelb', 'en-GB': 'Broom yellow' } },
    'RAL 1033': { hex: '#F3A505', names: { 'de-DE': 'Dahliengelb', 'en-GB': 'Dahlia yellow' } },
    'RAL 1034': { hex: '#EFA94A', names: { 'de-DE': 'Pastellgelb', 'en-GB': 'Pastel yellow' } },
    'RAL 1035': { hex: '#6A5D4D', names: { 'de-DE': 'Perlbeige', 'en-GB': 'Pearl beige' } },
    'RAL 1036': { hex: '#705335', names: { 'de-DE': 'Perlgold', 'en-GB': 'Pearl gold' } },
    'RAL 1037': { hex: '#F39F18', names: { 'de-DE': 'Sonnengelb', 'en-GB': 'Sun yellow' } },
    'RAL 2000': { hex: '#ED760E', names: { 'de-DE': 'Gelborange', 'en-GB': 'Yellow orange' } },
    'RAL 2001': { hex: '#C93C20', names: { 'de-DE': 'Rotorange', 'en-GB': 'Red orange' } },
    'RAL 2002': { hex: '#CB2821', names: { 'de-DE': 'Blutorange', 'en-GB': 'Vermilion' } },
    'RAL 2003': { hex: '#FF7514', names: { 'de-DE': 'Pastellorange', 'en-GB': 'Pastel orange' } },
    'RAL 2004': { hex: '#F44611', names: { 'de-DE': 'Reinorange', 'en-GB': 'Pure orange' } },
    'RAL 2005': { hex: '#FF2301', names: { 'de-DE': 'Leuchtorange', 'en-GB': 'Luminous orange' } },
    'RAL 2007': { hex: '#FFB200', names: { 'de-DE': 'Leuchthellorange', 'en-GB': 'Luminous bright orange' } },
    'RAL 2008': { hex: '#F35916', names: { 'de-DE': 'Hellrotorange', 'en-GB': 'Bright red orange' } },
    'RAL 2009': { hex: '#F54021', names: { 'de-DE': 'Verkehrsorange', 'en-GB': 'Traffic orange' } },
    'RAL 2010': { hex: '#D84B20', names: { 'de-DE': 'Signalorange', 'en-GB': 'Signal orange' } },
    'RAL 2011': { hex: '#EC7C26', names: { 'de-DE': 'Tieforange', 'en-GB': 'Deep orange' } },
    'RAL 2012': { hex: '#E55137', names: { 'de-DE': 'Lachsorange', 'en-GB': 'Salmon orange' } },
    'RAL 2013': { hex: '#C35831', names: { 'de-DE': 'Perlorange', 'en-GB': 'Pearl orange' } },
    'RAL 3000': { hex: '#A72920', names: { 'de-DE': 'Feuerrot', 'en-GB': 'Flame red' } },
    'RAL 3001': { hex: '#A52019', names: { 'de-DE': 'Signalrot', 'en-GB': 'Signal red' } },
    'RAL 3002': { hex: '#A2231D', names: { 'de-DE': 'Karminrot', 'en-GB': 'Carmine red' } },
    'RAL 3003': { hex: '#9B111E', names: { 'de-DE': 'Rubinrot', 'en-GB': 'Ruby red' } },
    'RAL 3004': { hex: '#75151E', names: { 'de-DE': 'Purpurrot', 'en-GB': 'Purple red' } },
    'RAL 3005': { hex: '#5E2129', names: { 'de-DE': 'Weinrot', 'en-GB': 'Wine red' } },
    'RAL 3007': { hex: '#412227', names: { 'de-DE': 'Schwarzrot', 'en-GB': 'Black red' } },
    'RAL 3009': { hex: '#642424', names: { 'de-DE': 'Oxidrot', 'en-GB': 'Oxide red' } },
    'RAL 3011': { hex: '#781F19', names: { 'de-DE': 'Braunrot', 'en-GB': 'Brown red' } },
    'RAL 3012': { hex: '#C1876B', names: { 'de-DE': 'Beigerot', 'en-GB': 'Beige red' } },
    'RAL 3013': { hex: '#A12312', names: { 'de-DE': 'Tomatenrot', 'en-GB': 'Tomato red' } },
    'RAL 3014': { hex: '#D36E70', names: { 'de-DE': 'Altrosa', 'en-GB': 'Antique pink' } },
    'RAL 3015': { hex: '#EA899A', names: { 'de-DE': 'Hellrosa', 'en-GB': 'Light pink' } },
    'RAL 3016': { hex: '#B32821', names: { 'de-DE': 'Korallenrot', 'en-GB': 'Coral red' } },
    'RAL 3017': { hex: '#E63244', names: { 'de-DE': 'Rosé', 'en-GB': 'Rose' } },
    'RAL 3018': { hex: '#D53032', names: { 'de-DE': 'Erdbeerrot', 'en-GB': 'Strawberry red' } },
    'RAL 3020': { hex: '#CC0605', names: { 'de-DE': 'Verkehrsrot', 'en-GB': 'Traffic red' } },
    'RAL 3022': { hex: '#D95030', names: { 'de-DE': 'Lachsrot', 'en-GB': 'Salmon pink' } },
    'RAL 3024': { hex: '#F80000', names: { 'de-DE': 'Leuchtrot', 'en-GB': 'Luminous red' } },
    'RAL 3026': { hex: '#FE0000', names: { 'de-DE': 'Leuchthellrot', 'en-GB': 'Luminous bright red' } },
    'RAL 3027': { hex: '#C51D34', names: { 'de-DE': 'Himbeerrot', 'en-GB': 'Raspberry red' } },
    'RAL 3028': { hex: '#CB3234', names: { 'de-DE': 'Reinrot', 'en-GB': 'Pure red' } },
    'RAL 3031': { hex: '#B32428', names: { 'de-DE': 'Orientrot', 'en-GB': 'Orient red' } },
    'RAL 3032': { hex: '#721422', names: { 'de-DE': 'Perlrubinrot', 'en-GB': 'Pearl ruby red' } },
    'RAL 3033': { hex: '#B44C43', names: { 'de-DE': 'Perlrosa', 'en-GB': 'Pearl pink' } },
    'RAL 4001': { hex: '#6D3461', names: { 'de-DE': 'Rotlila', 'en-GB': 'Red lilac' } },
    'RAL 4002': { hex: '#922B3E', names: { 'de-DE': 'Rotviolett', 'en-GB': 'Red violet' } },
    'RAL 4003': { hex: '#DE4C8A', names: { 'de-DE': 'Erikaviolett', 'en-GB': 'Heather violet' } },
    'RAL 4004': { hex: '#641C34', names: { 'de-DE': 'Bordeauxviolett', 'en-GB': 'Claret violet' } },
    'RAL 4005': { hex: '#6C4675', names: { 'de-DE': 'Blaulila', 'en-GB': 'Blue lilac' } },
    'RAL 4006': { hex: '#A03472', names: { 'de-DE': 'Verkehrspurpur', 'en-GB': 'Traffic purple' } },
    'RAL 4007': { hex: '#4A192C', names: { 'de-DE': 'Purpurviolett', 'en-GB': 'Purple violet' } },
    'RAL 4008': { hex: '#924E7D', names: { 'de-DE': 'Signalviolett', 'en-GB': 'Signal violet' } },
    'RAL 4009': { hex: '#A18594', names: { 'de-DE': 'Pastellviolett', 'en-GB': 'Pastel violet' } },
    'RAL 4010': { hex: '#CF3476', names: { 'de-DE': 'Telemagenta', 'en-GB': 'Telemagenta' } },
    'RAL 4011': { hex: '#8673A1', names: { 'de-DE': 'Perlviolett', 'en-GB': 'Pearl violet' } },
    'RAL 4012': { hex: '#6C6874', names: { 'de-DE': 'Perlbrombeer', 'en-GB': 'Pearl blackberry' } },
    'RAL 5000': { hex: '#354D73', names: { 'de-DE': 'Violettblau', 'en-GB': 'Violet blue' } },
    'RAL 5001': { hex: '#1F3438', names: { 'de-DE': 'Grünblau', 'en-GB': 'Green blue' } },
    'RAL 5002': { hex: '#20214F', names: { 'de-DE': 'Ultramarinblau', 'en-GB': 'Ultramarine blue' } },
    'RAL 5003': { hex: '#1D1E33', names: { 'de-DE': 'Saphirblau', 'en-GB': 'Sapphire blue' } },
    'RAL 5004': { hex: '#18171C', names: { 'de-DE': 'Schwarzblau', 'en-GB': 'Black blue' } },
    'RAL 5005': { hex: '#1E2460', names: { 'de-DE': 'Signalblau', 'en-GB': 'Signal blue' } },
    'RAL 5007': { hex: '#3E5F8A', names: { 'de-DE': 'Brillantblau', 'en-GB': 'Brilliant blue' } },
    'RAL 5008': { hex: '#26252D', names: { 'de-DE': 'Graublau', 'en-GB': 'Grey blue' } },
    'RAL 5009': { hex: '#025669', names: { 'de-DE': 'Azurblau', 'en-GB': 'Azure blue' } },
    'RAL 5010': { hex: '#0E294B', names: { 'de-DE': 'Enzianblau', 'en-GB': 'Gentian blue' } },
    'RAL 5011': { hex: '#231A24', names: { 'de-DE': 'Stahlblau', 'en-GB': 'Steel blue' } },
    'RAL 5012': { hex: '#3B83BD', names: { 'de-DE': 'Lichtblau', 'en-GB': 'Light blue' } },
    'RAL 5013': { hex: '#1E213D', names: { 'de-DE': 'Kobaltblau', 'en-GB': 'Cobalt blue' } },
    'RAL 5014': { hex: '#606E8C', names: { 'de-DE': 'Taubenblau', 'en-GB': 'Pigeon blue' } },
    'RAL 5015': { hex: '#2271B3', names: { 'de-DE': 'Himmelblau', 'en-GB': 'Sky blue' } },
    'RAL 5017': { hex: '#063971', names: { 'de-DE': 'Verkehrsblau', 'en-GB': 'Traffic blue' } },
    'RAL 5018': { hex: '#3F888F', names: { 'de-DE': 'Türkisblau', 'en-GB': 'Turquoise blue' } },
    'RAL 5019': { hex: '#1B5583', names: { 'de-DE': 'Capriblau', 'en-GB': 'Capri blue' } },
    'RAL 5020': { hex: '#1D334A', names: { 'de-DE': 'Ozeanblau', 'en-GB': 'Ocean blue' } },
    'RAL 5021': { hex: '#256D7B', names: { 'de-DE': 'Wasserblau', 'en-GB': 'Water blue' } },
    'RAL 5022': { hex: '#252850', names: { 'de-DE': 'Nachtblau', 'en-GB': 'Night blue' } },
    'RAL 5023': { hex: '#49678D', names: { 'de-DE': 'Fernblau', 'en-GB': 'Distant blue' } },
    'RAL 5024': { hex: '#5D9B9B', names: { 'de-DE': 'Pastellblau', 'en-GB': 'Pastel blue' } },
    'RAL 5025': { hex: '#2A6478', names: { 'de-DE': 'Perlenzian', 'en-GB': 'Pearl gentian blue' } },
    'RAL 5026': { hex: '#102C54', names: { 'de-DE': 'Perlnachtblau', 'en-GB': 'Pearl night blue' } },
    'RAL 6000': { hex: '#316650', names: { 'de-DE': 'Patinagrün', 'en-GB': 'Patina green' } },
    'RAL 6001': { hex: '#287233', names: { 'de-DE': 'Smaragdgrün', 'en-GB': 'Emerald green' } },
    'RAL 6002': { hex: '#2D572C', names: { 'de-DE': 'Laubgrün', 'en-GB': 'Leaf green' } },
    'RAL 6003': { hex: '#424632', names: { 'de-DE': 'Olivgrün', 'en-GB': 'Olive green' } },
    'RAL 6004': { hex: '#1F3A3D', names: { 'de-DE': 'Blaugrün', 'en-GB': 'Blue green' } },
    'RAL 6005': { hex: '#2F4538', names: { 'de-DE': 'Moosgrün', 'en-GB': 'Moss green' } },
    'RAL 6006': { hex: '#3E3B32', names: { 'de-DE': 'Grauoliv', 'en-GB': 'Grey olive' } },
    'RAL 6007': { hex: '#343B29', names: { 'de-DE': 'Flaschengrün', 'en-GB': 'Bottle green' } },
    'RAL 6008': { hex: '#39352A', names: { 'de-DE': 'Braungrün', 'en-GB': 'Brown green' } },
    'RAL 6009': { hex: '#31372B', names: { 'de-DE': 'Tannengrün', 'en-GB': 'Fir green' } },
    'RAL 6010': { hex: '#35682D', names: { 'de-DE': 'Grasgrün', 'en-GB': 'Grass green' } },
    'RAL 6011': { hex: '#587246', names: { 'de-DE': 'Resedagrün', 'en-GB': 'Reseda green' } },
    'RAL 6012': { hex: '#343E40', names: { 'de-DE': 'Schwarzgrün', 'en-GB': 'Black green' } },
    'RAL 6013': { hex: '#6C7156', names: { 'de-DE': 'Schilfgrün', 'en-GB': 'Reed green' } },
    'RAL 6014': { hex: '#47402E', names: { 'de-DE': 'Gelboliv', 'en-GB': 'Yellow olive' } },
    'RAL 6015': { hex: '#3B3C36', names: { 'de-DE': 'Schwarzoliv', 'en-GB': 'Black olive' } },
    'RAL 6016': { hex: '#1E5945', names: { 'de-DE': 'Türkisgrün', 'en-GB': 'Turquoise green' } },
    'RAL 6017': { hex: '#4C9141', names: { 'de-DE': 'Maigrün', 'en-GB': 'May green' } },
    'RAL 6018': { hex: '#57A639', names: { 'de-DE': 'Gelbgrün', 'en-GB': 'Yellow green' } },
    'RAL 6019': { hex: '#BDECB6', names: { 'de-DE': 'Weißgrün', 'en-GB': 'Pastel green' } },
    'RAL 6020': { hex: '#2E3A23', names: { 'de-DE': 'Chromoxidgrün', 'en-GB': 'Chrome green' } },
    'RAL 6021': { hex: '#89AC76', names: { 'de-DE': 'Blassgrün', 'en-GB': 'Pale green' } },
    'RAL 6022': { hex: '#25221B', names: { 'de-DE': 'Braunoliv', 'en-GB': 'Olive drab' } },
    'RAL 6024': { hex: '#308446', names: { 'de-DE': 'Verkehrsgrün', 'en-GB': 'Traffic green' } },
    'RAL 6025': { hex: '#3D642D', names: { 'de-DE': 'Farngrün', 'en-GB': 'Fern green' } },
    'RAL 6026': { hex: '#015D52', names: { 'de-DE': 'Opalgrün', 'en-GB': 'Opal green' } },
    'RAL 6027': { hex: '#84C3BE', names: { 'de-DE': 'Lichtgrün', 'en-GB': 'Light green' } },
    'RAL 6028': { hex: '#2C5545', names: { 'de-DE': 'Kieferngrün', 'en-GB': 'Pine green' } },
    'RAL 6029': { hex: '#20603D', names: { 'de-DE': 'Minzgrün', 'en-GB': 'Mint green' } },
    'RAL 6032': { hex: '#317F43', names: { 'de-DE': 'Signalgrün', 'en-GB': 'Signal green' } },
    'RAL 6033': { hex: '#497E76', names: { 'de-DE': 'Minttürkis', 'en-GB': 'Mint turquoise' } },
    'RAL 6034': { hex: '#7FB5B5', names: { 'de-DE': 'Pastelltürkis', 'en-GB': 'Pastel turquoise' } },
    'RAL 6035': { hex: '#1C542D', names: { 'de-DE': 'Perlgrün', 'en-GB': 'Pearl green' } },
    'RAL 6036': { hex: '#193737', names: { 'de-DE': 'Perlopalgrün', 'en-GB': 'Pearl opal green' } },
    'RAL 6037': { hex: '#008F39', names: { 'de-DE': 'Reingrün', 'en-GB': 'Pure green' } },
    'RAL 6038': { hex: '#00BB2D', names: { 'de-DE': 'Leuchtgrün', 'en-GB': 'Luminous green' } },
    'RAL 7000': { hex: '#78858B', names: { 'de-DE': 'Fehgrau', 'en-GB': 'Squirrel grey' } },
    'RAL 7001': { hex: '#8A9597', names: { 'de-DE': 'Silbergrau', 'en-GB': 'Silver grey' } },
    'RAL 7002': { hex: '#7E7B52', names: { 'de-DE': 'Olivgrau', 'en-GB': 'Olive grey' } },
    'RAL 7003': { hex: '#6C7059', names: { 'de-DE': 'Moosgrau', 'en-GB': 'Moss grey' } },
    'RAL 7004': { hex: '#969992', names: { 'de-DE': 'Signalgrau', 'en-GB': 'Signal grey' } },
    'RAL 7005': { hex: '#646B63', names: { 'de-DE': 'Mausgrau', 'en-GB': 'Mouse grey' } },
    'RAL 7006': { hex: '#6D6552', names: { 'de-DE': 'Beigegrau', 'en-GB': 'Beige grey' } },
    'RAL 7008': { hex: '#6A5F31', names: { 'de-DE': 'Khakigrau', 'en-GB': 'Khaki grey' } },
    'RAL 7009': { hex: '#4D5645', names: { 'de-DE': 'Grüngrau', 'en-GB': 'Green grey' } },
    'RAL 7010': { hex: '#4C514A', names: { 'de-DE': 'Zeltgrau', 'en-GB': 'Tarpaulin grey' } },
    'RAL 7011': { hex: '#434B4D', names: { 'de-DE': 'Eisengrau', 'en-GB': 'Iron grey' } },
    'RAL 7012': { hex: '#4E5754', names: { 'de-DE': 'Basaltgrau', 'en-GB': 'Basalt grey' } },
    'RAL 7013': { hex: '#464531', names: { 'de-DE': 'Braungrau', 'en-GB': 'Brown grey' } },
    'RAL 7015': { hex: '#434750', names: { 'de-DE': 'Schiefergrau', 'en-GB': 'Slate grey' } },
    'RAL 7016': { hex: '#293133', names: { 'de-DE': 'Anthrazitgrau', 'en-GB': 'Anthracite grey' } },
    'RAL 7021': { hex: '#23282B', names: { 'de-DE': 'Schwarzgrau', 'en-GB': 'Black grey' } },
    'RAL 7022': { hex: '#332F2C', names: { 'de-DE': 'Umbragrau', 'en-GB': 'Umbra grey' } },
    'RAL 7023': { hex: '#686C5E', names: { 'de-DE': 'Betongrau', 'en-GB': 'Concrete grey' } },
    'RAL 7024': { hex: '#474A51', names: { 'de-DE': 'Graphitgrau', 'en-GB': 'Graphite grey' } },
    'RAL 7026': { hex: '#2F353B', names: { 'de-DE': 'Granitgrau', 'en-GB': 'Granite grey' } },
    'RAL 7030': { hex: '#8B8C7A', names: { 'de-DE': 'Steingrau', 'en-GB': 'Stone grey' } },
    'RAL 7031': { hex: '#474B4E', names: { 'de-DE': 'Blaugrau', 'en-GB': 'Blue grey' } },
    'RAL 7032': { hex: '#B8B799', names: { 'de-DE': 'Kieselgrau', 'en-GB': 'Pebble grey' } },
    'RAL 7033': { hex: '#7D8471', names: { 'de-DE': 'Zementgrau', 'en-GB': 'Cement grey' } },
    'RAL 7034': { hex: '#8F8B66', names: { 'de-DE': 'Gelbgrau', 'en-GB': 'Yellow grey' } },
    'RAL 7035': { hex: '#CBD0CC', names: { 'de-DE': 'Lichtgrau', 'en-GB': 'Light grey' } },
    'RAL 7036': { hex: '#7F7679', names: { 'de-DE': 'Platingrau', 'en-GB': 'Platinum grey' } },
    'RAL 7037': { hex: '#7D7F7D', names: { 'de-DE': 'Staubgrau', 'en-GB': 'Dusty grey' } },
    'RAL 7038': { hex: '#B5B8B1', names: { 'de-DE': 'Achatgrau', 'en-GB': 'Agate grey' } },
    'RAL 7039': { hex: '#6C6960', names: { 'de-DE': 'Quarzgrau', 'en-GB': 'Quartz grey' } },
    'RAL 7040': { hex: '#9DA1AA', names: { 'de-DE': 'Fenstergrau', 'en-GB': 'Window grey' } },
    'RAL 7042': { hex: '#8D948D', names: { 'de-DE': 'Verkehrsgrau A', 'en-GB': 'Traffic grey A' } },
    'RAL 7043': { hex: '#4E5452', names: { 'de-DE': 'Verkehrsgrau B', 'en-GB': 'Traffic grey B' } },
    'RAL 7044': { hex: '#CAC4B0', names: { 'de-DE': 'Seidengrau', 'en-GB': 'Silk grey' } },
    'RAL 7045': { hex: '#909090', names: { 'de-DE': 'Telegrau 1', 'en-GB': 'Telegrey 1' } },
    'RAL 7046': { hex: '#82898F', names: { 'de-DE': 'Telegrau 2', 'en-GB': 'Telegrey 2' } },
    'RAL 7047': { hex: '#D0D0D0', names: { 'de-DE': 'Telegrau 4', 'en-GB': 'Telegrey 4' } },
    'RAL 7048': { hex: '#898176', names: { 'de-DE': 'Perlmausgrau', 'en-GB': 'Pearl mouse grey' } },
    'RAL 8000': { hex: '#826C34', names: { 'de-DE': 'Grünbraun', 'en-GB': 'Green brown' } },
    'RAL 8001': { hex: '#955F20', names: { 'de-DE': 'Ockerbraun', 'en-GB': 'Ochre brown' } },
    'RAL 8002': { hex: '#6C3B2A', names: { 'de-DE': 'Signalbraun', 'en-GB': 'Signal brown' } },
    'RAL 8003': { hex: '#734222', names: { 'de-DE': 'Lehmbraun', 'en-GB': 'Clay brown' } },
    'RAL 8004': { hex: '#8E402A', names: { 'de-DE': 'Kupferbraun', 'en-GB': 'Copper brown' } },
    'RAL 8007': { hex: '#59351F', names: { 'de-DE': 'Rehbraun', 'en-GB': 'Fawn brown' } },
    'RAL 8008': { hex: '#6F4F28', names: { 'de-DE': 'Olivbraun', 'en-GB': 'Olive brown' } },
    'RAL 8011': { hex: '#5B3A29', names: { 'de-DE': 'Nussbraun', 'en-GB': 'Nut brown' } },
    'RAL 8012': { hex: '#592321', names: { 'de-DE': 'Rotbraun', 'en-GB': 'Red brown' } },
    'RAL 8014': { hex: '#382C1E', names: { 'de-DE': 'Sepiabraun', 'en-GB': 'Sepia brown' } },
    'RAL 8015': { hex: '#633A34', names: { 'de-DE': 'Kastanienbraun', 'en-GB': 'Chestnut brown' } },
    'RAL 8016': { hex: '#4C2F27', names: { 'de-DE': 'Mahagonibraun', 'en-GB': 'Mahogany brown' } },
    'RAL 8017': { hex: '#45322E', names: { 'de-DE': 'Schokoladenbraun', 'en-GB': 'Chocolate brown' } },
    'RAL 8019': { hex: '#403A3A', names: { 'de-DE': 'Graubraun', 'en-GB': 'Grey brown' } },
    'RAL 8022': { hex: '#212121', names: { 'de-DE': 'Schwarzbraun', 'en-GB': 'Black brown' } },
    'RAL 8023': { hex: '#A65E2E', names: { 'de-DE': 'Orangebraun', 'en-GB': 'Orange brown' } },
    'RAL 8024': { hex: '#79553D', names: { 'de-DE': 'Beigebraun', 'en-GB': 'Beige brown' } },
    'RAL 8025': { hex: '#755C48', names: { 'de-DE': 'Blassbraun', 'en-GB': 'Pale brown' } },
    'RAL 8028': { hex: '#4E3B31', names: { 'de-DE': 'Terrabraun', 'en-GB': 'Terra brown' } },
    'RAL 8029': { hex: '#763C28', names: { 'de-DE': 'Perlkupfer', 'en-GB': 'Pearl copper' } },
    'RAL 9001': { hex: '#FDF4E3', names: { 'de-DE': 'Cremeweiß', 'en-GB': 'Cream' } },
    'RAL 9002': { hex: '#E7EBDA', names: { 'de-DE': 'Grauweiß', 'en-GB': 'Grey white' } },
    'RAL 9003': { hex: '#F4F4F4', names: { 'de-DE': 'Signalweiß', 'en-GB': 'Signal white' } },
    'RAL 9004': { hex: '#282828', names: { 'de-DE': 'Signalschwarz', 'en-GB': 'Signal black' } },
    'RAL 9005': { hex: '#0A0A0D', names: { 'de-DE': 'Tiefschwarz', 'en-GB': 'Jet black' } },
    'RAL 9006': { hex: '#A5A5A5', names: { 'de-DE': 'Weißaluminium', 'en-GB': 'White aluminium' } },
    'RAL 9007': { hex: '#8F8F8F', names: { 'de-DE': 'Graualuminium', 'en-GB': 'Grey aluminium' } },
    'RAL 9010': { hex: '#FFFFFF', names: { 'de-DE': 'Reinweiß', 'en-GB': 'Pure white' } },
    'RAL 9011': { hex: '#1C1C1C', names: { 'de-DE': 'Graphitschwarz', 'en-GB': 'Graphite black' } },
    'RAL 9012': { hex: '#FFFDE6', names: { 'de-DE': 'Reinraumweiß', 'en-GB': 'Clean room white' } },
    'RAL 9016': { hex: '#F6F6F6', names: { 'de-DE': 'Verkehrsweiß', 'en-GB': 'Traffic white' } },
    'RAL 9017': { hex: '#1E1E1E', names: { 'de-DE': 'Verkehrsschwarz', 'en-GB': 'Traffic black' } },
    'RAL 9018': { hex: '#D7D7D7', names: { 'de-DE': 'Papyrusweiß', 'en-GB': 'Papyrus white' } },
    'RAL 9022': { hex: '#9C9C9C', names: { 'de-DE': 'Perlhellgrau', 'en-GB': 'Pearl light grey' } },
    'RAL 9023': { hex: '#828282', names: { 'de-DE': 'Perldunkelgrau', 'en-GB': 'Pearl dark grey' } },
};
